version: '2'

services:
  jenkins:
    image: local/jenkins
    build: ./build
    volumes:
      - home:/var/jenkins_home
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  home:
