version: '3.5'

services:
  jenkins:
    image: local/jenkins
    build: ./build
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      demonet:
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  demonet:
    name: ansible-demo-scenario