version: '2'

services:
  jenkins:
    image: local/jenkins
    build: ./build
    volumes:
      - home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "${HOST_PORT}:8080"
      - 50000:50000
    restart: unless-stopped

volumes:
  home:
