version: '2'

services:
  gitea:
    image: gitea/gitea
    environment:
      - ROOT_URL=http://git.example.org:3000/
    volumes:
      - data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    restart: unless-stopped

volumes:
  data:
