version: '3.5'
services:
  gitea:
    image: gitea/gitea
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - demonet
    restart: unless-stopped

volumes:
  gitea_data:
    
networks:
  demonet:
    name: ansible-demo-scenario