version: '3.5'
services:
  gitea:
    image: gitea/gitea
    volumes:
      - ./volumes/gitea/data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - demonet
    restart: always

networks:
  demonet:
    name: ansible-demo-scenario